"""Add maintenance dispatch log table

Revision ID: 285b2a1659cb
Revises: 6d294bceadb7
Create Date: 2025-12-31 17:38:49.867866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285b2a1659cb'
down_revision: Union[str, None] = '6d294bceadb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_dispatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_dispatch_logs_id'), 'maintenance_dispatch_logs', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_dispatch_logs_org_id'), 'maintenance_dispatch_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_maintenance_dispatch_logs_request_id'), 'maintenance_dispatch_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_maintenance_dispatch_logs_vendor_id'), 'maintenance_dispatch_logs', ['vendor_id'], unique=False)
    
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_constraint('uq_properties_property_id', type_='unique')
        batch_op.create_index('ix_properties_property_id', ['property_id'], unique=True)
    
    op.alter_column('vendors', 'average_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'average_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_index('ix_properties_property_id')
        batch_op.create_unique_constraint('uq_properties_property_id', ['property_id'])
    
    op.drop_index(op.f('ix_maintenance_dispatch_logs_vendor_id'), table_name='maintenance_dispatch_logs')
    op.drop_index(op.f('ix_maintenance_dispatch_logs_request_id'), table_name='maintenance_dispatch_logs')
    op.drop_index(op.f('ix_maintenance_dispatch_logs_org_id'), table_name='maintenance_dispatch_logs')
    op.drop_index(op.f('ix_maintenance_dispatch_logs_id'), table_name='maintenance_dispatch_logs')
    op.drop_table('maintenance_dispatch_logs')
    # ### end Alembic commands ###
