"""Add SLA tracking fields to maintenance requests

Revision ID: 540260d16211
Revises: 285b2a1659cb
Create Date: 2025-12-31 17:41:01.563831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540260d16211'
down_revision: Union[str, None] = '285b2a1659cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('sla_due_at', sa.DateTime(), nullable=False))
    op.add_column('maintenance_requests', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('escalated', sa.Boolean(), nullable=False))
    
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_constraint('uq_properties_property_id', type_='unique')
        batch_op.create_index('ix_properties_property_id', ['property_id'], unique=True)
    
    op.alter_column('vendors', 'average_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'average_rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_index('ix_properties_property_id')
        batch_op.create_unique_constraint('uq_properties_property_id', ['property_id'])
    
    op.drop_column('maintenance_requests', 'escalated')
    op.drop_column('maintenance_requests', 'resolved_at')
    op.drop_column('maintenance_requests', 'accepted_at')
    op.drop_column('maintenance_requests', 'sla_due_at')
    # ### end Alembic commands ###
