"""Add vendor performance metrics and assignment counter model

Revision ID: 6d294bceadb7
Revises: 051228096c94
Create Date: 2025-12-31 17:28:51.768585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d294bceadb7'
down_revision: Union[str, None] = '051228096c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_assignment_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('last_assigned_vendor_id', sa.Integer(), nullable=True),
    sa.Column('assignment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_assigned_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_assignment_counters_id'), 'vendor_assignment_counters', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_assignment_counters_org_id'), 'vendor_assignment_counters', ['org_id'], unique=False)
    op.drop_index('ix_billing_update_retries_next_retry_at', table_name='billing_update_retries')
    op.create_index(op.f('ix_billing_update_retries_id'), 'billing_update_retries', ['id'], unique=False)
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_constraint('uq_properties_property_id', type_='unique')
        batch_op.create_index('ix_properties_property_id', ['property_id'], unique=True)
    op.add_column('vendors', sa.Column('total_jobs_assigned', sa.Integer(), nullable=False))
    op.add_column('vendors', sa.Column('jobs_completed', sa.Integer(), nullable=False))
    op.add_column('vendors', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'average_rating')
    op.drop_column('vendors', 'jobs_completed')
    op.drop_column('vendors', 'total_jobs_assigned')
    with op.batch_alter_table('properties') as batch_op:
        batch_op.drop_index('ix_properties_property_id')
        batch_op.create_unique_constraint('uq_properties_property_id', ['property_id'])
    op.drop_index(op.f('ix_billing_update_retries_id'), table_name='billing_update_retries')
    op.create_index('ix_billing_update_retries_next_retry_at', 'billing_update_retries', ['next_retry_at'], unique=False)
    op.drop_index(op.f('ix_vendor_assignment_counters_org_id'), table_name='vendor_assignment_counters')
    op.drop_index(op.f('ix_vendor_assignment_counters_id'), table_name='vendor_assignment_counters')
    op.drop_table('vendor_assignment_counters')
    # ### end Alembic commands ###
